apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
